export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './custom-fields.service';
import { CustomFieldsService } from './custom-fields.service';
export * from './custom-fields.serviceInterface';
export * from './inventory-transactions.service';
import { InventoryTransactionsService } from './inventory-transactions.service';
export * from './inventory-transactions.serviceInterface';
export * from './invite.service';
import { InviteService } from './invite.service';
export * from './invite.serviceInterface';
export * from './item-types.service';
import { ItemTypesService } from './item-types.service';
export * from './item-types.serviceInterface';
export * from './permissions.service';
import { PermissionsService } from './permissions.service';
export * from './permissions.serviceInterface';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './products.serviceInterface';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './roles.serviceInterface';
export * from './stock.service';
import { StockService } from './stock.service';
export * from './stock.serviceInterface';
export * from './suppliers.service';
import { SuppliersService } from './suppliers.service';
export * from './suppliers.serviceInterface';
export * from './two-factor.service';
import { TwoFactorService } from './two-factor.service';
export * from './two-factor.serviceInterface';
export * from './users.service';
import { UsersService } from './users.service';
export * from './users.serviceInterface';
export const APIS = [AuthService, CustomFieldsService, InventoryTransactionsService, InviteService, ItemTypesService, PermissionsService, ProductsService, RolesService, StockService, SuppliersService, TwoFactorService, UsersService];
