export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './item-types.service';
import { ItemTypesService } from './item-types.service';
export * from './item-types.serviceInterface';
export * from './permissions.service';
import { PermissionsService } from './permissions.service';
export * from './permissions.serviceInterface';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './products.serviceInterface';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './roles.serviceInterface';
export * from './suppliers.service';
import { SuppliersService } from './suppliers.service';
export * from './suppliers.serviceInterface';
export * from './users.service';
import { UsersService } from './users.service';
export * from './users.serviceInterface';
export const APIS = [AuthService, ItemTypesService, PermissionsService, ProductsService, RolesService, SuppliersService, UsersService];
