/**
 * Fachschaften-ERP.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LoginRequest } from '../model/models';
import { RegisterRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiAuthLoginPostRequestParams {
    loginRequest: LoginRequest;
}

export interface ApiAuthRegisterPostRequestParams {
    registerRequest: RegisterRequest;
}


export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    apiAuthLoginPost(requestParameters: ApiAuthLoginPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    apiAuthLogoutPost(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    apiAuthMeGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiAuthRegisterPost(requestParameters: ApiAuthRegisterPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
