/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BookingDto } from '../model/models';
import { BookingSummaryDto } from '../model/models';
import { CashIncomeRequest } from '../model/models';
import { CashIncomeSource } from '../model/models';
import { ItemUpsertRequestOfBookingDto } from '../model/models';
import { TaxArea } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiBookingsCashIncomePostRequestParams {
    cashIncomeRequest: CashIncomeRequest;
}

export interface ApiBookingsGetRequestParams {
    year?: number;
    month?: number;
    taxArea?: TaxArea;
    cashBookId?: string;
    source?: CashIncomeSource;
}

export interface ApiBookingsIdDeleteRequestParams {
    id: string;
}

export interface ApiBookingsIdGetRequestParams {
    id: string;
}

export interface ApiBookingsPostRequestParams {
    itemUpsertRequestOfBookingDto: ItemUpsertRequestOfBookingDto;
}

export interface ApiBookingsSummaryGetRequestParams {
    year?: number;
}


export interface BookingsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    apiBookingsCashIncomePost(requestParameters: ApiBookingsCashIncomePostRequestParams, extraHttpRequestParams?: any): Observable<Array<BookingDto>>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiBookingsGet(requestParameters: ApiBookingsGetRequestParams, extraHttpRequestParams?: any): Observable<Array<BookingDto>>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiBookingsIdDelete(requestParameters: ApiBookingsIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiBookingsIdGet(requestParameters: ApiBookingsIdGetRequestParams, extraHttpRequestParams?: any): Observable<BookingDto>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiBookingsPost(requestParameters: ApiBookingsPostRequestParams, extraHttpRequestParams?: any): Observable<BookingDto>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiBookingsSummaryGet(requestParameters: ApiBookingsSummaryGetRequestParams, extraHttpRequestParams?: any): Observable<BookingSummaryDto>;

}
