/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { BookingCategoryDto } from '../model/models';
import { ItemUpsertRequestOfBookingCategoryDto } from '../model/models';
import { TaxArea } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiBookingCategoriesGetRequestParams {
    taxArea?: TaxArea;
}

export interface ApiBookingCategoriesIdDeleteRequestParams {
    id: string;
}

export interface ApiBookingCategoriesIdGetRequestParams {
    id: string;
}

export interface ApiBookingCategoriesPostRequestParams {
    itemUpsertRequestOfBookingCategoryDto: ItemUpsertRequestOfBookingCategoryDto;
}


export interface BookingCategoriesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    apiBookingCategoriesGet(requestParameters: ApiBookingCategoriesGetRequestParams, extraHttpRequestParams?: any): Observable<Array<BookingCategoryDto>>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiBookingCategoriesIdDelete(requestParameters: ApiBookingCategoriesIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiBookingCategoriesIdGet(requestParameters: ApiBookingCategoriesIdGetRequestParams, extraHttpRequestParams?: any): Observable<BookingCategoryDto>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiBookingCategoriesPost(requestParameters: ApiBookingCategoriesPostRequestParams, extraHttpRequestParams?: any): Observable<BookingCategoryDto>;

}
