/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CashBookDto } from '../model/models';
import { CashBookTransferRequest } from '../model/models';
import { ItemUpsertRequestOfCashBookUpsertDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiCashBooksIdClosePostRequestParams {
    id: string;
}

export interface ApiCashBooksIdDeleteRequestParams {
    id: string;
}

export interface ApiCashBooksIdGetRequestParams {
    id: string;
}

export interface ApiCashBooksPostRequestParams {
    itemUpsertRequestOfCashBookUpsertDto: ItemUpsertRequestOfCashBookUpsertDto;
}

export interface ApiCashBooksTransferPostRequestParams {
    cashBookTransferRequest: CashBookTransferRequest;
}


export interface CashBooksServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    apiCashBooksGet(extraHttpRequestParams?: any): Observable<Array<CashBookDto>>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiCashBooksIdClosePost(requestParameters: ApiCashBooksIdClosePostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiCashBooksIdDelete(requestParameters: ApiCashBooksIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiCashBooksIdGet(requestParameters: ApiCashBooksIdGetRequestParams, extraHttpRequestParams?: any): Observable<CashBookDto>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiCashBooksPost(requestParameters: ApiCashBooksPostRequestParams, extraHttpRequestParams?: any): Observable<CashBookDto>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiCashBooksTransferPost(requestParameters: ApiCashBooksTransferPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
