/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CustomFieldDto } from '../model/models';
import { ItemUpsertRequestOfCustomFieldDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiCustomFieldsIdDeleteRequestParams {
    id: string;
}

export interface ApiCustomFieldsIdGetRequestParams {
    id: string;
}

export interface ApiCustomFieldsPostRequestParams {
    itemUpsertRequestOfCustomFieldDto: ItemUpsertRequestOfCustomFieldDto;
}

export interface ApiCustomFieldsTypeTypeIdGetRequestParams {
    typeId: string;
}


export interface CustomFieldsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    apiCustomFieldsGet(extraHttpRequestParams?: any): Observable<Array<CustomFieldDto>>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiCustomFieldsIdDelete(requestParameters: ApiCustomFieldsIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiCustomFieldsIdGet(requestParameters: ApiCustomFieldsIdGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiCustomFieldsPost(requestParameters: ApiCustomFieldsPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiCustomFieldsTypeTypeIdGet(requestParameters: ApiCustomFieldsTypeTypeIdGetRequestParams, extraHttpRequestParams?: any): Observable<Array<CustomFieldDto>>;

}
