/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DeliveryDto } from '../model/models';
import { DeliveryOverviewDto } from '../model/models';
import { ItemUpsertRequestOfDeliveryDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiDeliveriesIdDeleteRequestParams {
    id: string;
}

export interface ApiDeliveriesIdGetRequestParams {
    id: string;
}

export interface ApiDeliveriesPostRequestParams {
    itemUpsertRequestOfDeliveryDto: ItemUpsertRequestOfDeliveryDto;
}


export interface DeliveriesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    apiDeliveriesGet(extraHttpRequestParams?: any): Observable<Array<DeliveryOverviewDto>>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiDeliveriesIdDelete(requestParameters: ApiDeliveriesIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiDeliveriesIdGet(requestParameters: ApiDeliveriesIdGetRequestParams, extraHttpRequestParams?: any): Observable<DeliveryDto>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiDeliveriesPost(requestParameters: ApiDeliveriesPostRequestParams, extraHttpRequestParams?: any): Observable<DeliveryDto>;

}
