/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { InventoryTransactionDto } from '../model/models';
import { ItemUpsertRequestOfInventoryTransactionDto } from '../model/models';
import { SimpleInventoryTransactionDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiInventoryTransactionsIdGetRequestParams {
    id: string;
}

export interface ApiInventoryTransactionsPostRequestParams {
    itemUpsertRequestOfInventoryTransactionDto: ItemUpsertRequestOfInventoryTransactionDto;
}

export interface ApiInventoryTransactionsProductProductIdGetRequestParams {
    productId: string;
}


export interface InventoryTransactionsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    apiInventoryTransactionsIdGet(requestParameters: ApiInventoryTransactionsIdGetRequestParams, extraHttpRequestParams?: any): Observable<InventoryTransactionDto>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiInventoryTransactionsPost(requestParameters: ApiInventoryTransactionsPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiInventoryTransactionsProductProductIdGet(requestParameters: ApiInventoryTransactionsProductProductIdGetRequestParams, extraHttpRequestParams?: any): Observable<Array<SimpleInventoryTransactionDto>>;

}
