/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AcceptInviteRequest } from '../model/models';
import { AcceptInviteResult } from '../model/models';
import { InviteRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiInvitesAcceptPostRequestParams {
    acceptInviteRequest: AcceptInviteRequest;
}

export interface ApiInvitesPostRequestParams {
    inviteRequest: InviteRequest;
}


export interface InviteServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    apiInvitesAcceptPost(requestParameters: ApiInvitesAcceptPostRequestParams, extraHttpRequestParams?: any): Observable<AcceptInviteResult>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiInvitesPost(requestParameters: ApiInvitesPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
