/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CustomFieldDto } from '../model/models';
import { ItemTypeDto } from '../model/models';
import { UpsertItemTypeRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiItemTypesIdDeleteRequestParams {
    id: string;
}

export interface ApiItemTypesIdGetRequestParams {
    id: string;
}

export interface ApiItemTypesIdPutRequestParams {
    id: string;
    upsertItemTypeRequest: UpsertItemTypeRequest;
}

export interface ApiItemTypesPostRequestParams {
    upsertItemTypeRequest: UpsertItemTypeRequest;
}

export interface ApiItemTypesTypeIdCustomFieldsGetRequestParams {
    typeId: string;
}


export interface ItemTypesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    apiItemTypesGet(extraHttpRequestParams?: any): Observable<Array<ItemTypeDto>>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiItemTypesIdDelete(requestParameters: ApiItemTypesIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiItemTypesIdGet(requestParameters: ApiItemTypesIdGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiItemTypesIdPut(requestParameters: ApiItemTypesIdPutRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiItemTypesPost(requestParameters: ApiItemTypesPostRequestParams, extraHttpRequestParams?: any): Observable<ItemTypeDto>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiItemTypesTypeIdCustomFieldsGet(requestParameters: ApiItemTypesTypeIdCustomFieldsGetRequestParams, extraHttpRequestParams?: any): Observable<Array<CustomFieldDto>>;

}
