/**
 * Fachschaften-ERP.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { UpsertProductRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiProductsIdDeleteRequestParams {
    id: string;
}

export interface ApiProductsIdGetRequestParams {
    id: string;
}

export interface ApiProductsIdPutRequestParams {
    id: string;
    upsertProductRequest: UpsertProductRequest;
}


export interface ProductsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    apiProductsGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiProductsIdDelete(requestParameters: ApiProductsIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiProductsIdGet(requestParameters: ApiProductsIdGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiProductsIdPut(requestParameters: ApiProductsIdPutRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
