/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ItemUpsertRequestOfProductDto } from '../model/models';
import { ProductDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiProductsIdDeleteRequestParams {
    id: string;
}

export interface ApiProductsIdGetRequestParams {
    id: string;
}

export interface ApiProductsPostRequestParams {
    itemUpsertRequestOfProductDto: ItemUpsertRequestOfProductDto;
}


export interface ProductsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    apiProductsGet(extraHttpRequestParams?: any): Observable<Array<ProductDto>>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiProductsIdDelete(requestParameters: ApiProductsIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiProductsIdGet(requestParameters: ApiProductsIdGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiProductsPost(requestParameters: ApiProductsPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
