/**
 * Fachschaften-ERP.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateRoleRequest } from '../model/models';
import { RoleDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiRolesIdDeleteRequestParams {
    id: string;
}

export interface ApiRolesIdGetRequestParams {
    id: string;
}

export interface ApiRolesIdPermissionsGetRequestParams {
    id: string;
}

export interface ApiRolesIdPermissionsPermissionDeleteRequestParams {
    id: string;
    permission: string;
}

export interface ApiRolesIdPermissionsPermissionPostRequestParams {
    id: string;
    permission: string;
}

export interface ApiRolesPostRequestParams {
    createRoleRequest: CreateRoleRequest;
}


export interface RolesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    apiRolesGet(extraHttpRequestParams?: any): Observable<Array<RoleDto>>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiRolesIdDelete(requestParameters: ApiRolesIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiRolesIdGet(requestParameters: ApiRolesIdGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiRolesIdPermissionsGet(requestParameters: ApiRolesIdPermissionsGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiRolesIdPermissionsPermissionDelete(requestParameters: ApiRolesIdPermissionsPermissionDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiRolesIdPermissionsPermissionPost(requestParameters: ApiRolesIdPermissionsPermissionPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiRolesPost(requestParameters: ApiRolesPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
