/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { StockOverviewDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface StockServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    apiStockGet(extraHttpRequestParams?: any): Observable<Array<StockOverviewDto>>;

}
