/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { SupplierDto } from '../model/models';
import { UpsertSupplierRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiSuppliersIdDeleteRequestParams {
    id: string;
}

export interface ApiSuppliersIdGetRequestParams {
    id: string;
}

export interface ApiSuppliersPostRequestParams {
    upsertSupplierRequest: UpsertSupplierRequest;
}


export interface SuppliersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    apiSuppliersGet(extraHttpRequestParams?: any): Observable<Array<SupplierDto>>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiSuppliersIdDelete(requestParameters: ApiSuppliersIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiSuppliersIdGet(requestParameters: ApiSuppliersIdGetRequestParams, extraHttpRequestParams?: any): Observable<Array<SupplierDto>>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiSuppliersPost(requestParameters: ApiSuppliersPostRequestParams, extraHttpRequestParams?: any): Observable<SupplierDto>;

}
