/**
 * Fachschaften-ERP.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { UpsertSupplierRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiSuppliersIdDeleteRequestParams {
    id: string;
}

export interface ApiSuppliersIdGetRequestParams {
    id: string;
}

export interface ApiSuppliersIdPutRequestParams {
    id: string;
    upsertSupplierRequest: UpsertSupplierRequest;
}


export interface SuppliersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    apiSuppliersGet(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiSuppliersIdDelete(requestParameters: ApiSuppliersIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiSuppliersIdGet(requestParameters: ApiSuppliersIdGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiSuppliersIdPut(requestParameters: ApiSuppliersIdPutRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
