/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Setup2FaRequest } from '../model/models';
import { Setup2FaResult } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiAuth2faSetupPostRequestParams {
    setup2FaRequest: Setup2FaRequest;
}


export interface TwoFactorServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    apiAuth2faSetupDelete(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    apiAuth2faSetupGet(extraHttpRequestParams?: any): Observable<Setup2FaResult>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiAuth2faSetupPost(requestParameters: ApiAuth2faSetupPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
