/**
 * Fachschaften-ERP.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ChangePasswordRequest } from '../model/models';
import { UpsertUserRequest } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface ApiUsersIdChangePasswordPostRequestParams {
    id: string;
    changePasswordRequest: ChangePasswordRequest;
}

export interface ApiUsersIdDeleteRequestParams {
    id: string;
}

export interface ApiUsersIdGetRequestParams {
    id: string;
}

export interface ApiUsersIdPermissionsGetRequestParams {
    id: any;
}

export interface ApiUsersIdPermissionsPermissionDeleteRequestParams {
    id: string;
    permission: any;
}

export interface ApiUsersIdPermissionsPermissionPostRequestParams {
    id: string;
    permission: any;
}

export interface ApiUsersIdPostRequestParams {
    id: string;
    upsertUserRequest: UpsertUserRequest;
}

export interface ApiUsersIdRolesGetRequestParams {
    id: string;
}

export interface ApiUsersIdRolesRoleDeleteRequestParams {
    id: string;
    role: string;
}

export interface ApiUsersIdRolesRoleIdPostRequestParams {
    id: string;
    roleId: string;
}


export interface UsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
*/
    apiUsersGet(extraHttpRequestParams?: any): Observable<any>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUsersIdChangePasswordPost(requestParameters: ApiUsersIdChangePasswordPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUsersIdDelete(requestParameters: ApiUsersIdDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUsersIdGet(requestParameters: ApiUsersIdGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUsersIdPermissionsGet(requestParameters: ApiUsersIdPermissionsGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUsersIdPermissionsPermissionDelete(requestParameters: ApiUsersIdPermissionsPermissionDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUsersIdPermissionsPermissionPost(requestParameters: ApiUsersIdPermissionsPermissionPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUsersIdPost(requestParameters: ApiUsersIdPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUsersIdRolesGet(requestParameters: ApiUsersIdRolesGetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUsersIdRolesRoleDelete(requestParameters: ApiUsersIdRolesRoleDeleteRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    apiUsersIdRolesRoleIdPost(requestParameters: ApiUsersIdRolesRoleIdPostRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
