/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CashBookTransferRequest { 
    fromCashBookId: string;
    toCashBookId: string;
    amount: number;
    date: string;
    description: string;
}

