/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeliveryOverviewDto { 
    id: string;
    supplierId: string;
    supplierName: string;
    deliveryDate: string;
    documentNumber: string | null;
    receiptUrl: string | null;
    positionCount: number;
    totalQuantity: number;
    totalAmount: number;
}

