/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InventoryTransactionType } from './inventory-transaction-type';


export interface InventoryTransactionDto { 
    id: string;
    productId: string;
    date: string;
    type: InventoryTransactionType;
    quantity: number;
    amount: number;
    note: string | null;
}



