/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InviteRequest { 
    userName: string;
    email: string | null;
    roles: Array<string> | null;
    require2Fa: boolean;
}

