/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BookingCategoryDto } from './booking-category-dto';


export interface ItemUpsertRequestOfBookingCategoryDto { 
    id?: string | null;
    value: BookingCategoryDto | null;
}

