/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductDto } from './product-dto';


export interface ItemUpsertRequestOfProductDto { 
    id?: string | null;
    value: ProductDto | null;
}

