/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CashBookUpsertDto } from './cash-book-upsert-dto';


export interface ItemUpsertRequestOfCashBookUpsertDto { 
    id?: string | null;
    value: CashBookUpsertDto | null;
}

