/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InventoryTransactionDto } from './inventory-transaction-dto';


export interface ItemUpsertRequestOfInventoryTransactionDto { 
    id?: string | null;
    value: InventoryTransactionDto | null;
}

