/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MeDto { 
    id: string;
    userName: string;
    email: string;
    roles: Array<string>;
    permissions: Array<string>;
    claims: Array<string>;
}

