/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductDto { 
    id?: string | null;
    stock: number;
    name: string;
    purchasePrice: number;
    internalSellingPrice: number;
    externalSellingPrice: number;
    lowStockThreshold: number;
    trackStock: boolean;
    customFieldValues: any | null;
    itemTypeId: string;
    supplierId?: string | null;
}

