/**
 * Fachschaften-ERP.Api | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InventoryTransactionType } from './inventory-transaction-type';


export interface StockUpdatePositionDto { 
    productId: string;
    newStock: number;
    type: InventoryTransactionType;
    note: string | null;
}



