/**
 * Fachschaften-ERP.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpsertProductRequest { 
    name: string;
    itemTypeId: string;
    supplierId: string | null;
    purchasePrice: number;
    sellingPrice: number;
    stock: number;
    lowStockThreshold: number;
    trackStock: boolean;
    customFieldValues: string | null;
}

