/**
 * Fachschaften-ERP.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpsertProductRequest { 
    name: any | null;
    itemTypeId: any | null;
    supplierId: any | null;
    purchasePrice: any | null;
    sellingPrice: any | null;
    stock: any | null;
    lowStockThreshold: any | null;
    trackStock: any | null;
    customFieldValues: any | null;
}

